#!/bin/bash

source_dir="$(cd "$(dirname "$BASH_SOURCE")" && pwd)"
working_dir=$(pwd)
filename="${working_dir}/config_$(date +'%y-%m-%d--%H%M').txt"
groups_filename="${working_dir}/groups_$(date +'%y-%m-%d--%H%M').csv"

touch "$filename"

echo " "
echo "Running this command is going to create a file called ${filename}" 
echo "with configuration details needed for running the scripts here. Please answer" 
echo "carefully (although you can of course edit the config file later)."
echo ""
echo "(beginning of file)"
echo "----------------------------------------------------"
echo "----------------------------------------------------"
echo "This is a file where you need to input some paths for the scripts to use."
echo "No quotation marks or anything like that."
echo "Generated on $(date)."
echo "----------------------------------------------------"
echo "PATHS RELATED TO THE DATA"
echo "----------------------------------------------------"
echo "1. Path to root data directory"
echo "(Enter an answer)"
read rootdir
echo ""
echo "2. Organism being imaged (human, mouse, or rat)"
echo "(Enter an answer)"
read organism
echo ""
echo "3. Diffusion metrics to generate (comma separated; options include: FA, MD, AD, RD, QA, ODI, NDI)"
echo "(Enter an answer)"
read volumes
echo ""
echo "----------------------------------------------------"
echo "PATHS RELATED TO SCRIPT INSTALLATION"
echo "----------------------------------------------------"
echo "4. Path to directory containing the scripts"
scripts_dir=${source_dir}/scripts/
echo $scripts_dir
echo "(True by default; edit manually in config if false...)"
echo ""
echo "5. Path to container"
echo "(Enter an answer)"
read container_path
echo ""
echo "6. Paths for slurm job notice emails and out files"
echo "Mail type (NONE, ALL, FAIL)"
echo "(Enter an answer)"
read mail_type
echo "Mail user (email address)"
echo "(Enter an answer)"
read mail_user
echo "Path to directory where slurm output files will be dumped"
echo "(Enter an answer)"
read slurm_out_path
echo "----------------------------------------------------"
echo "----------------------------------------------------"
echo "(end of file)"

{
    echo "######################################################"
    echo "######################################################"
    echo "# This is a file where you need to input some paths for the scripts to use."
    echo "# No quotation marks or anything like that."
    echo "# Generated on $(date)."
    echo "######################################################"
    echo "# PATHS RELATED TO THE DATA"
    echo "######################################################"
    echo "# 1. Path to root data directory"
    echo "rootdir=${rootdir}"
    echo ""
    echo "# 2. Path to groups file"
    echo "groups_file=${groups_filename}"
    echo ""
    echo "######################################################"
    echo "# PATHS RELATED TO SCRIPT INSTALLATION"
    echo "######################################################"
    echo "# 3. Path to directory containing the scripts"
    echo "scripts_dir=${scripts_dir}"
    echo ""
    echo "# 4. Path to container"
    echo "container_path=${container_path}"
    echo ""
    echo "# 5. Paths for slurm job notice emails and out files"
    echo "mailtype=${mail_type}"
    echo "mailuser=${mail_user}"
    echo "slurm_out_path=${slurm_out_path}"
    echo ""
    echo "######################################################"
    echo "# SETTINGS"
    echo "######################################################"
    echo "# 6. Organism being imaged (human, mouse, or rat)"
    echo "organism=${organism}"
    echo ""
    echo "# 7. Diffusion metrics to generate (comma separated; options include: FA,MD,AD,RD,QA,ODI,NDI,MK)"
    echo "volumes=${volumes}"
    echo ""
    echo "# 8. Should MP-PCA denoising be applied to the diffusion image?"
    echo "do_mppca=1"
    echo ""
    echo "# 9. Should the 'bad slice removal' script be applied to the diffusion image?"
    echo "do_slice=0"
    echo ""
    echo "######################################################"
    echo "# MISCELLANEOUS"
    echo "######################################################"
    echo "# 10. IDs of any atlas ROIs to specifically track in DSI (comma separated, or just X if none; e.g., 102,500,12)"
    echo "special_ids=X"
    echo ""
    echo "######################################################"
    echo "######################################################"
} > "$filename"

echo "Wrote config file to: $filename"

echo "subject,group,timepoint,filename" > ${groups_filename}
for dir in "$rootdir"/*/; do
    basename "$dir" | sed 's/^/,,,/' >> ${groups_filename}
done

echo "Wrote groups file to ${groups_filename}"
