#!/bin/bash

#########################################
# 0 - GET USER INPUT THEN FIND ROOTDIR AND SCRIPTS DIR FROM CONFIG
#########################################

config_path=""
step=""
design=""
vba_tbss=""

while [[ "$#" -gt 0 ]]; do
  case $1 in
    --config) config_path="$2"; shift ;;
    --step) step="$2"; shift ;;
    --design) design="$2"; shift ;;
    *) echo "Unknown parameter: $1" >&2; exit 1 ;;
  esac
  shift
done

if [[ -z "$config_path" || -z "$step" ]]; then
  echo " "
  echo "Usage: bash $0 --config <path/to/config.txt> --step <fit|check_fit|reg|roi|combine_roi_outputs|vba_avg|vba_compare|tract> "
  echo " "
  echo "  --config : give the full path to the config file created by MAKE_CONFIG; all parameters are set in this file, which can be manually edited."
  echo "  --step   : choose the step of the process to initiate. Options and their descriptions are as follows -"
  echo "               > fit                 : perform fitting needed to generate volumes listed in config file."
  echo "               > check_fit           : if there is any possibility that the fitting didn't occur correctly, check with this and re-initiate "
  echo "                                       fitting where it didn't occur properly."
  echo "               > reg                 : register to atlas; atlas to use determined by organism set in config."
  echo "               > roi                 : compute signal of metrics in all regions in the atlas."
  echo "               > combine_roi_outputs : once all roi scripts are done, combine them into one manageable csv output."
  echo "               > vba_avg             : make images from averaging all volumes together, for later usage in a template or visualization. Must "
  echo "                                       do this as prerequisite to vba_compare."
  echo "               > vba_compare         : do a statistical comparison between groups as they are defined in the groups file generated by "
  echo "                                       MAKE_CONFIG. For this, must also set design argument."
  echo "               > tract               : do deterministic tractography with dsi_studio."
  echo "  --design : used and required only by step vba_compare; options are -"
  echo "               > baseline            : no timepoints, just compare metrics"
  echo "               > delta               : for 2 timepoints only - compute delta"
  echo "               > longitudinal        : multiple timepoints" 
  echo "               > baseline_tract      : for tbss output comparisons - no timepoints, just compare metrics"
  echo "               > delta_tract         : for tbss output comparisons - for 2 timepoints only - compute delta"
  echo "               > longitudinal_tract  : for tbss output comparisons - multiple timepoints" 
  echo " "
  exit 1
fi


filedir="$(cd "$(dirname "$BASH_SOURCE")" && pwd)"
source ${filedir}/READ_CONFIG.sh $config_path

for file in $(find "$scripts_dir" -type f); do
    sed -i "s|^#SBATCH --mail-type=.*|#SBATCH --mail-type=${mailtype}|" "$file"
    sed -i "s|^#SBATCH --mail-user=.*|#SBATCH --mail-user=${mailuser}|" "$file"
    sed -i "s|^#SBATCH --output=.*|#SBATCH --output=${slurm_out_path}/slurm-%j.out|" "$file"
done

if [[ "$step" == "fit" ]]; then
    noddi=0
    for volume in "${volumes[@]}"; do
        if [[ "$volume" == "NDI" || "$volume" == "ODI" ]]; then
            noddi=1
            break
        fi
    done

    if [[ "$noddi" == 0 ]]; then
        #########################################
        # 1 - DTI FITTING
        #########################################
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Doing DTI fitting"
        
        # Change job length
        sed -i 's/^#SBATCH --time .*/#SBATCH --time 6:00:00/' "${scripts_dir}/ODTB-0_job-submitter.sbatch"
        
        cd $rootdir
        mkdir batch_output
        subdirs=$(ls)
        n_subdirs=`find . -mindepth 1 -maxdepth 1 -type d | wc -l`
        
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Identified $n_subdirs subdirectories in root directory for initial fitting in ${rootdir}"
        count=1
        
        for d in $subdirs
            do
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running initial fitting script on subdir $count called $d."
                sbatch ${scripts_dir}/ODTB-0_job-submitter.sbatch --config $config_path --script ${scripts_dir}/ODTB-1a_fit.sh --dir $d
            done
            
    elif [[ "$noddi" == 1 ]]; then
        #########################################
        # 1x - DTI AND NODDI FITTING - MDT only works here for now.
        #########################################
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Doing DTI and NODDI fitting"
        
        cd $rootdir
        mkdir batch_output
        subdirs=$(ls)
        n_subdirs=`find . -mindepth 1 -maxdepth 1 -type d | wc -l`
        
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Identified $n_subdirs subdirectories in root directory for initial fitting in ${rootdir}"
        count=1
        
        for d in $subdirs
            do
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running initial fitting script on subdir $count called $d."
                sbatch ${scripts_dir}/ODTB-1x_fit-with-mdt.sbatch --config $config_path --dir $d
                count=$(($count+1))
            done
    
    fi

elif [[ "$step" == "check_fit" ]]; then
    #########################################
    # 1b - GET MISSED DIRECTORIES FROM INITIAL FITTING
    #########################################
    # Because sometimes py-opencl throws an error (device not found)
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Checking all directories for DTI/NODDI output..."
    
    cd ${rootdir}/batch_output
    echo $rootdir
    subdirs=$(ls)
    mkdir ../batch2
    
    for d in $subdirs
    do
    	if [ ! -f ${d}/ODI.nii.gz ]; then
    		echo "for ${d} - no NODDI output"
    		rm -r ${d}
    		cp -r ../${d//_output} ../batch2
    	fi
    done
    
    cd ../batch2
    rm -r */output
    rm */fullbinmask.nii.gz
    rm */raw_dwi_censored.nii.gz
    rm */raw_dwi_censored_mppca.nii.gz
    rm */tensorperfect_dwi.nii.gz
    
    cd ${rootdir}/batch2
    rootdir=${rootdir}/batch2
    subdirs=$(ls)
    n_subdirs=`find . -mindepth 1 -maxdepth 1 -type d | wc -l`
    
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Identified $n_subdirs subdirectories from check which still need to be fitted in ${rootdir}"
    count=1
    
    for d in $subdirs
        do
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running initial fitting script on subdir $count called $d."
            sbatch ${scripts_dir}/ODTB-1x_fit-with-mdt.sbatch --config $config_path --dir $d --rerun 1
            count=$(($count+1))
        done

elif [[ "$step" == "combine_fit_outputs" ]]; then
    #########################################
    # 1c - COMBINE ORIGINAL FIT AND NEW FIT OUTPUTS
    #########################################
    # Because sometimes py-opencl throws an error (device not found)
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Combining outputs from fit and check_fit"
    
    mv ${rootdir}/batch2/batch_output/* ${rootdir}/batch_output/
    rm -r ${rootdir}/batch2/batch_output
    rm -r ${rootdir}/batch2

elif [[ "$step" == "reg" ]]; then
    #########################################
    # 2 - REGISTRATION
    #########################################
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Doing registration"
    
    cd ${rootdir}/batch_output
    subdirs=$(ls)
    n_subdirs=`find . -mindepth 1 -maxdepth 1 -type d | wc -l`
    
    # Change job length
    sed -i 's/^#SBATCH --time .*/#SBATCH --time 48:00:00/' "${scripts_dir}/ODTB-0_job-submitter.sbatch"
    
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Identified $n_subdirs subdirectories in root directory for registration in ${rootdir}/batch_output"
    echo " "
    count=1
    cp ${scripts_dir}/ODTB-2_register.sh ${rootdir}/batch_output/ODTB-2_register.sh
    mkdir batch_reg_output
    
    for d in $subdirs
    do
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running registration script on subdir $count called $d."
        sbatch ${scripts_dir}/ODTB-0_job-submitter.sbatch --config $config_path --script ${scripts_dir}/ODTB-2_register.sh --dir $d
        count=$(($count+1))
    done
    
elif [[ "$step" == "reg_apply" ]]; then
    #########################################
    # 2 - REGISTRATION
    #########################################
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Doing registration"
    
    cd ${rootdir}/batch_output
    subdirs=$(ls)
    n_subdirs=`find . -mindepth 1 -maxdepth 1 -type d | wc -l`
    
    # Change job length
    sed -i 's/^#SBATCH --time .*/#SBATCH --time 48:00:00/' "${scripts_dir}/ODTB-0_job-submitter.sbatch"
    
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Identified $n_subdirs subdirectories in root directory for registration in ${rootdir}/batch_output"
    echo " "
    count=1
    cp ${scripts_dir}/ODTB-2_register.sh ${rootdir}/batch_output/ODTB-2_register.sh
    mkdir batch_reg_output
    
    for d in $subdirs
    do
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running registration script on subdir $count called $d."
        bash ${scripts_dir}/ODTB-0_job-submitter.sbatch --config $config_path --script ${scripts_dir}/ODTB-2x_register-apply.sh --dir $d
        count=$(($count+1))
    done
    
elif [[ "$step" == "reg_studyFA" ]]; then
    #########################################
    # 2 - REGISTRATION
    #########################################
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Re-doing registration with study-specific FA template"
    
    cd ${rootdir}/batch_output
    subdirs=$(ls)
    n_subdirs=`find . -mindepth 1 -maxdepth 1 -type d | wc -l`
    
    # Change job length
    sed -i 's/^#SBATCH --time .*/#SBATCH --time 48:00:00/' "${scripts_dir}/ODTB-0_job-submitter.sbatch"
    
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Identified $n_subdirs subdirectories in root directory for registration in ${rootdir}/batch_output"
    echo " "
    count=1
    cp ${scripts_dir}/ODTB-2_register.sh ${rootdir}/batch_output/ODTB-2_register.sh
    mkdir batch_reg_output2
    
    for d in $subdirs
    do
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running registration script on subdir $count called $d."
        sbatch ${scripts_dir}/ODTB-0_job-submitter.sbatch --config $config_path --script ${scripts_dir}/ODTB-2x_register-studyFA.sh --dir $d
        count=$(($count+1))
    done
    
elif [[ "$step" == "reg_switch" ]]; then
    #########################################
    # 2 - REGISTRATION - SWITCH USED
    #########################################
    if [ -d "${rootdir}/batch_output/batch_reg_output2" ]; then
         echo "[$(date '+%Y-%m-%d %H:%M:%S')] Switching used reg from orig to fa"
    
        cd ${rootdir}/batch_output
        mv batch_reg_output batch_reg_output_ORIG
        mv batch_reg_output2 batch_reg_output
        
        subdirs=$(ls)
        n_subdirs=`find . -mindepth 1 -maxdepth 1 -type d | wc -l`
        
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Switched batch_reg_output, now switching reg in each directory"
        
        for d in $subdirs
        do
            cd $d
            mv reg reg_ORIG
            mv reg2 reg
            cd ..
        done
        
    else
         echo "[$(date '+%Y-%m-%d %H:%M:%S')] While trying to switch used reg directory, didn't find reg2 directories"
    fi
    
    
elif [[ "$step" == "mk_clip" ]]; then
    #########################################
    # 2 - REGISTRATION
    #########################################
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Doing registration"
    
    cd ${rootdir}/batch_output/batch_reg_output
    subdirs=$(ls)
    n_subdirs=`find . -mindepth 1 -maxdepth 1 -type d | wc -l`
    
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Identified $n_subdirs subdirectories in root directory for MK clipping in ${rootdir}/batch_output"
    echo " "
    count=1
    
    for d in $subdirs
    do
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running registration script on subdir $count called $d."
        bash ${scripts_dir}/ODTB-0_job-submitter.sbatch --config $config_path --script ${scripts_dir}/ODTB-misc_mk-clip.sh --dir $d
        count=$(($count+1))
    done

elif [[ "$step" == "roi" ]]; then
    #########################################
    # 3a1 - ROI-BASED ANALYSIS
    #########################################
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Doing ROI-based analysis"
    
    postreg_root=${rootdir}/batch_output/batch_reg_output/
    output_dir="${postreg_root}/roi_analysis_output/"
    mkdir $output_dir
    cd ${postreg_root}
    subdirs=$(ls)
    n_subdirs=`find . -mindepth 1 -maxdepth 1 -type d | wc -l`
    
    # Change job length
    sed -i 's/^#SBATCH --time .*/#SBATCH --time 00:30:00/' "${scripts_dir}/ODTB-0_job-submitter.sbatch"
    
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Identified $n_subdirs subdirectories in root directory for roi analysis in $rootdir"
    echo " "
    
    count=1
    for d in $subdirs
    do
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running roi_counter script on subdir $count called $d."
        sbatch ${scripts_dir}/ODTB-0_job-submitter.sbatch --config $config_path --script ${scripts_dir}/ODTB-3a_roi-counter.sh --dir $d
        count=$(($count+1))
    done

elif [[ "$step" == "combine_roi_outputs" ]]; then
    #########################################
    # 3a2 - ROI-BASED ANALYSIS - COMBINE OUTPUTS
    #########################################
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Combining outputs from roi-based analysis"
    output_dir="${rootdir}/batch_output/batch_reg_output/roi_analysis_output/"
    cd $rootdir
    
    singularity exec $container_path /opt/conda/envs/diffusionmritoolkit/bin/python ${scripts_dir}/ODTB-3c_roi-out-combiner.py $output_dir "${volumes[@]}"
    find "$output_dir" -type f ! -name '*combined*' -print0 | xargs -0 -I {} rm {}

elif [[ "$step" == "roi_distr_compare" ]]; then
    #########################################
    # 3a1 - ROI-BASED ANALYSIS
    #########################################
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Doing ROI-based analysis"
    
    postreg_root=${rootdir}/batch_output/batch_reg_output/
    output_dir="${postreg_root}/roi_dist_output/"
    mkdir $output_dir
    cd ${postreg_root}

        if [[ "$design" == "baseline" ]]
        then
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] roi_distr_compare - comparing groups using a BASELINE (single timepoint, multi group) design"
            for vol in "${volumes[@]}"
            do
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Making roi_distr_compare maps for ${vol}"
                singularity exec $container_path /opt/conda/envs/diffusionmritoolkit/bin/python ${scripts_dir}/ODTB-3d_roi-compare-dist.py \
                    --rootdir $reg_output_dir \
                    --mask $mask_path \
                    --outdir $output_dir \
                    --groups $groups_file \
                    --organism $organism \
                    --atlas_path $atlas_path \
                    --vt ${vol} \
                    --design "baseline"
            done
        elif [[ "$design" == "delta" ]]
        then
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] roi_distr_compare - comparing groups using a DELTA (two timepoint, multi group) design"
            for vol in "${volumes[@]}"
            do
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Making roi_distr_compare maps for ${vol}"
                singularity exec $container_path /opt/conda/envs/diffusionmritoolkit/bin/python ${scripts_dir}/ODTB-3d_roi-compare-dist.py \
                    --rootdir $reg_output_dir \
                    --mask $mask_path \
                    --outdir $output_dir \
                    --groups $groups_file \
                    --organism $organism \
                    --atlas_path $atlas_path \
                    --vt ${vol} \
                    --design "delta"
            done
        fi

elif [[ "$step" == "vba_avg" || "$step" == "vba_compare" ]]; then
    #########################################
    # 3b - VOXEL-BASED ANALYSIS
    #########################################
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Voxel-based analysis"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Making directories etc for VBA output"
    
    reg_output_dir=${rootdir}/batch_output/batch_reg_output/
    
    cd $reg_output_dir
    dir=vba/avg_volumes/
    tmap_dir="${reg_output_dir}/vba/tmaps/"
    baseline_tmap_dir="${reg_output_dir}/vba/baseline_tmaps/"
    tbss_tmap_dir="${reg_output_dir}/tbss/tmaps/"
    tbss_baseline_tmap_dir="${reg_output_dir}/tbss/baseline_tmaps/"
    mkdir -p vba
    mkdir -p $dir
    mkdir -p $tmap_dir
    mkdir -p $baseline_tmap_dir
    mkdir -p "${tmap_dir}/individual_diffs"
    mkdir -p $tbss_tmap_dir
    mkdir -p "${tbss_tmap_dir}/individual_diffs"
    mkdir -p $tbss_baseline_tmap_dir
    
    labels_path="${reg_output_dir}/${dir}/atlas_labels.nii.gz"
    mask_path="${reg_output_dir}/${dir}/atlas_mask.nii.gz"
    
    if [[ "$step" == "vba_avg" ]]
    then
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Voxel-based analysis - making average volumes"
        if [[ "$organism" == "mouse" ]]
        then
            cp ${atlas_path}/mouse/P56_MASK_100um.nii.gz $mask_path
        fi
        if [[ "$organism" == "rat" ]]
        then
            cp ${atlas_path}/rat/WHS_SD_rat_BRAIN_MASK.nii.gz $mask_path
        fi
        if [[ "$organism" == "human" ]]
        then
            fslmaths ${atlas_path}/human/HarvardOxford-cort-maxprob-thr50-1mm.nii.gz \
                -add ${atlas_path}/human/HarvardOxford-cort-maxprob-thr50-1mm.nii.gz \
                -bin $mask_path
        fi
        
        for vol in "${volumes[@]}"
        do
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] Making an average of ${vol} images"
            mkdir "${dir}/${vol}"
            find "$reg_output_dir" -type f -name "*_output_${vol}_reg.nii.gz" -print0 | xargs -0 -I {} cp {} "${dir}/${vol}"
            singularity exec $container_path /opt/conda/envs/diffusionmritoolkit/bin/python ${scripts_dir}/ODTB-4b_avg-vol.py $dir $vol $mask_path $organism
            rm -r "${dir}/${vol}"
        done
    fi
    
    if [[ "$step" == "vba_compare" ]]
    then
        if [[ "$design" == "baseline" ]]
        then
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] Voxel-based analysis - comparing groups using a BASELINE (single-timepoint) design"
            for vol in "${volumes[@]}"
            do
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Making stat maps for ${vol}"
                singularity exec $container_path /opt/conda/envs/diffusionmritoolkit/bin/python ${scripts_dir}/ODTB-4c_statmaps.py \
                    --rootdir $reg_output_dir \
                    --mask $mask_path \
                    --outdir $baseline_tmap_dir \
                    --avg_vol_dir "${reg_output_dir}/vba/avg_volumes/" \
                    --groups $groups_file \
                    --organism $organism \
                    --vt ${vol} \
                    --design "baseline"
            done
        elif [[ "$design" == "delta" ]]
        then
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] Voxel-based analysis - comparing groups using a DELTA (two timepoint; post vs. pre) between-groups design"
            for vol in "${volumes[@]}"
            do
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Making stat maps for ${vol}"
                singularity exec $container_path /opt/conda/envs/diffusionmritoolkit/bin/python ${scripts_dir}/ODTB-4c_statmaps.py \
                    --rootdir $reg_output_dir \
                    --mask $mask_path \
                    --outdir $tmap_dir \
                    --avg_vol_dir "${reg_output_dir}/vba/avg_volumes/" \
                    --groups $groups_file \
                    --organism $organism \
                    --vt ${vol} \
                    --design "delta"
            done
        elif [[ "$design" == "longitudinal" ]]
        then
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] Voxel-based analysis - comparing groups using a LONGITUDINAL (multi timepoint, multi group) design"
            for vol in "${volumes[@]}"
            do
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Making stat maps for ${vol}"
                singularity exec $container_path /opt/conda/envs/diffusionmritoolkit/bin/python ${scripts_dir}/ODTB-4c_statmaps.py \
                    --rootdir $reg_output_dir \
                    --mask $mask_path \
                    --outdir $tmap_dir \
                    --avg_vol_dir "${reg_output_dir}/vba/avg_volumes/" \
                    --groups $groups_file \
                    --organism $organism \
                    --vt ${vol} \
                    --design "longitudinal"
            done
        elif [[ "$design" == "baseline_tract" ]]
        then
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] Voxel-based analysis - comparing groups using a BASELINE (single-timepoint) design"
            for vol in "${volumes[@]}"
            do
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Making stat maps for ${vol}"
                singularity exec $container_path /opt/conda/envs/diffusionmritoolkit/bin/python ${scripts_dir}/ODTB-6a_tbss-compare.py \
                    --rootdir $reg_output_dir \
                    --mask $mask_path \
                    --outdir $tbss_baseline_tmap_dir \
                    --avg_vol_dir "${reg_output_dir}/vba/avg_volumes/" \
                    --groups $groups_file \
                    --organism $organism \
                    --vt ${vol} \
                    --design "baseline"
            done
        elif [[ "$design" == "delta_tract" ]]
        then
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] Voxel-based analysis - comparing groups using a DELTA (two timepoint; post vs. pre) between-groups design"
            for vol in "${volumes[@]}"
            do
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Making stat maps for ${vol}"
                singularity exec $container_path /opt/conda/envs/diffusionmritoolkit/bin/python ${scripts_dir}/ODTB-6a_tbss-compare.py \
                    --rootdir $reg_output_dir \
                    --mask $mask_path \
                    --outdir $tbss_tmap_dir \
                    --avg_vol_dir "${reg_output_dir}/vba/avg_volumes/" \
                    --groups $groups_file \
                    --organism $organism \
                    --vt ${vol} \
                    --design "delta"
            done
        elif [[ "$design" == "longitudinal_tract" ]]
        then
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] Voxel-based analysis - comparing groups using a LONGITUDINAL (multi timepoint, multi group) design"
            for vol in "${volumes[@]}"
            do
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Making stat maps for ${vol}"
                singularity exec $container_path /opt/conda/envs/diffusionmritoolkit/bin/python ${scripts_dir}/ODTB-6a_tbss-compare.py \
                    --rootdir $reg_output_dir \
                    --mask $mask_path \
                    --outdir $tbss_tmap_dir \
                    --avg_vol_dir "${reg_output_dir}/vba/avg_volumes/" \
                    --groups $groups_file \
                    --organism $organism \
                    --vt ${vol} \
                    --design "longitudinal"
            done
        else
            echo "To use vba_compare, you must set --design to be baseline, delta, or longitudinal based on your experimental design. Run bash RUN_SCRIPT.sh with no args to see explanation."
            exit 1
        fi
        
    fi

elif [[ "$step" == "tract" ]]; then
    #########################################
    # 3c - TRACTOGRAPHY
    #########################################
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Doing tractography-based analysis"
    
    # Change job length
    sed -i 's/^#SBATCH --time .*/#SBATCH --time 0:30:00/' "${scripts_dir}/ODTB-0_job-submitter.sbatch"

    cd $rootdir
    subdirs=$(ls)
    n_subdirs=`find . -mindepth 1 -maxdepth 1 -type d | wc -l`
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Identified $n_subdirs subdirectories in root directory for DSI fiber tracking in $rootdir"
    echo " "
    count=1
    
    for d in $subdirs
    do
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running tractography script on subdir $count called $d."
        sbatch ${scripts_dir}/ODTB-0_job-submitter.sbatch --config $config_path --script ${scripts_dir}/ODTB-5a_dsi.sh --dir $d
        count=$(($count+1))
    done

elif [[ "$step" == "tbss" ]]; then
    #########################################
    # 3c - TRACT-BASED SPATIAL STATISTICS
    #########################################
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Doing tract-based spatial statistics"
    
    # Change job length
    sed -i 's/^#SBATCH --time .*/#SBATCH --time 0:10:00/' "${scripts_dir}/ODTB-0_job-submitter.sbatch"
    
    cd ${rootdir}/batch_output/batch_reg_output
    subdirs=$(ls)
    n_subdirs=`find . -mindepth 1 -maxdepth 1 -type d | wc -l`
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Identified $n_subdirs subdirectories in root directory for TBSS in ${rootdir}/batch_output/batch_reg_output"
    echo " "
    count=1
    
    for d in $subdirs
    do
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running TBSS script on subdir $count called $d."
        sbatch ${scripts_dir}/ODTB-0_job-submitter.sbatch --config $config_path --script ${scripts_dir}/ODTB-6a_tbss.sh --dir $d
        count=$(($count+1))
    done

else
    echo "Choose a valid option! [fit | check_fit | combine_fit_outputs | reg | roi | combine_roi_outputs | vba_avg | vba_compare | tract | tbss]"
    echo " "
    echo "Usage: bash $0 --config <path/to/config.txt> --step <fit|check_fit|reg|roi|combine_roi_outputs|vba_avg|vba_compare|tract> "
    echo " "
    echo "  --config : give the full path to the config file created by MAKE_CONFIG; all parameters are set in this file, which can be manually edited."
    echo "  --step   : choose the step of the process to initiate. Options and their descriptions are as follows -"
    echo "               > fit                 : perform fitting needed to generate volumes listed in config file."
    echo "               > check_fit           : if there is any possibility that the fitting didn't occur correctly, check with this and re-initiate "
    echo "                                       fitting where it didn't occur properly."
    echo "               > reg                 : register to atlas; atlas to use determined by organism set in config."
    echo "               > roi                 : compute signal of metrics in all regions in the atlas."
    echo "               > combine_roi_outputs : once all roi scripts are done, combine them into one manageable csv output."
    echo "               > vba_avg             : make images from averaging all volumes together, for later usage in a template or visualization. Must "
    echo "                                       do this as prerequisite to vba_compare."
    echo "               > vba_compare         : do a statistical comparison between groups as they are defined in the groups file generated by "
    echo "                                       MAKE_CONFIG. For this, must also set design argument."
    echo "               > tract               : do deterministic tractography with dsi_studio."
    echo "  --design : used and required only by step vba_compare; options are -"
    echo "               > baseline            : no timepoints, just compare metrics"
    echo "               > delta               : for 2 timepoints only - compute delta"
    echo "               > longitudinal        : multiple timepoints" 
  echo " "
    exit 1
fi

